### ISSUE TITLE
매니저 신청 승인/거절  Approval 페이지 재작업

### ISSUE THREAD

**Issue by DICEPT** [MINI-FASTCAMPUS5/scheduler-front#42]
# 기능

매니저 행사 신청 승인/거절 

# 적용되는 페이지 Approval의 작업을 보충하고 수정합니다.

src/pages/manager/approval

# 추가 설명

1. 매니저 신청 승인/거절 페이지 리스트 영역 재작업
2. 행사 수정 모달 지정 작업 및 From 추가 작업

# 예상 시작일

2023/08/03

# 예상 완료일

2023/08/03

**Comment by peacepiece7** [comment]
완료된 작업 태그로 변경해 주셨기 떄문에 해당 이슈는 닫습니다.
