### ISSUE TITLE
사용자 회원정보 수정 페이지 API 연동

### ISSUE THREAD

**Issue by 0299bang** [MINI-FASTCAMPUS5/scheduler-front#52]
# 기능
회원정보 api 연동
# 적용되는 페이지
/user/edit
# 추가 설명
회원정보 변경, 보내기, 받기 가능하도록 구현
# 예상 시작일
2023/08/06
# 예상 완료일
2023/08/07

**Comment by peacepiece7** [comment]
완료된 작업으로 이슈를 닫습니다.
